"""Eligibility checking engine for TANSEED Grant."""

from typing import List, Dict, Any, Tuple
from tanseed_rag.pipeline import TanseedPipeline


class EligibilityChecker:
    """Checks user startup data against TANSEED guidelines using RAG context."""

    def __init__(self, pipeline: TanseedPipeline):
        self.pipeline = pipeline

    def check_eligibility(self, user_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Perform a comprehensive eligibility check.
        Returns a report with status per field and overall recommendation.
        """
        report = {
            "overall_status": "PASS",
            "checks": {},
            "recommendation": ""
        }

        # 1. Registration Type
        reg_type = user_data.get("registration_type", "").lower()
        sector = user_data.get("sector", "")
        
        # Enhanced query incorporating sector if available
        query = "What are the eligible registration types for TANSEED?"
        if sector:
            query = f"What are the eligible registration types for {sector} startups under TANSEED?"
            
        context = self.pipeline.get_context(query, top_k=2)
        is_valid_reg = any(t in reg_type for t in ["private limited", "llp", "partnership"])
        report["checks"]["registration_type"] = {
            "status": "PASS" if is_valid_reg else "FAIL",
            "value": reg_type,
            "justification": "Must be Private Limited, LLP, or Partnership Firm. " + ("Context: " + context[:200] + "...")
        }

        # 2. Location
        location = user_data.get("location", "").lower()
        is_tn = "tamil nadu" in location or "tn" in location
        report["checks"]["location"] = {
            "status": "PASS" if is_tn else "FAIL",
            "value": location,
            "justification": "Must be registered in or relocating to Tamil Nadu."
        }

        # 3. Ownership
        ownership = float(user_data.get("indian_ownership_pct", 0))
        report["checks"]["indian_ownership_pct"] = {
            "status": "PASS" if ownership >= 51 else "FAIL",
            "value": ownership,
            "justification": f"Must be at least 51% owned by Indian promoters. Current: {ownership}%"
        }

        # 4. Profit
        profit = float(user_data.get("avg_profit_3yr_lakhs", 0))
        report["checks"]["avg_profit_3yr_lakhs"] = {
            "status": "PASS" if profit < 5 else "FAIL",
            "value": profit,
            "justification": f"Average profit for last 3 years must be less than INR 5 lakh. Current: {profit} lakh"
        }

        # 5. Recognition (Startup India & TANSIM)
        has_tansim = user_data.get("tansim_registration", False)
        has_dpiit = user_data.get("dpiit_recognition", False)
        report["checks"]["recognition"] = {
            "status": "PASS" if (has_tansim and has_dpiit) else "FAIL",
            "value": f"TANSIM: {has_tansim}, DPIIT: {has_dpiit}",
            "justification": "Must be registered with both TANSIM and Startup India (DPIIT)."
        }

        # Update overall status
        for check in report["checks"].values():
            if check["status"] == "FAIL":
                report["overall_status"] = "FAIL"
                break

        if report["overall_status"] == "PASS":
            report["recommendation"] = "The startup appears to be eligible for the TANSEED grant. Proceed to application."
        else:
            report["recommendation"] = "The startup does not meet one or more eligibility criteria. Address the failing items before applying."

        return report

    def draft_application(self, user_data: Dict[str, Any], project_desc: str) -> str:
        """
        Drafts application content by combining user project description with RAG context.
        """
        context = self.pipeline.get_context("What should be included in a TANSEED grant pitch deck and business plan?", top_k=3)
        
        draft = f"""# TANSEED GRANT APPLICATION DRAFT
Startup: {user_data.get('name', 'N/A')}

## 1. Executive Summary
{project_desc}

## 2. Alignment with TANSEED Guidelines
Based on our guidelines:
{context}

---
*Draft generated by TANSEED RAG Pipeline*
"""
        return draft
